---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for pcc.paloaltonetworks.com/v1alpha1, Kind: Console
  ##
  - apiGroups:
      - pcc.paloaltonetworks.com
    resources:
      - consoles
      - consoles/status
      - consoles/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for pcc.paloaltonetworks.com/v1alpha1, Kind: Defender
  ##
  - apiGroups:
      - pcc.paloaltonetworks.com
    resources:
      - defenders
      - defenders/status
      - defenders/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for pcc.paloaltonetworks.com/v1alpha1, Kind: ConsoleDefender
  ##
  - apiGroups:
      - pcc.paloaltonetworks.com
    resources:
      - consoledefenders
      - consoledefenders/status
      - consoledefenders/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
#+kubebuilder:scaffold:rules
